# Navigation Links
# Documentation: https://docs.hugoblox.com/getting-started/page-builder/

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /#projects
    weight: 20
  - name: Publications
    url: /publication/
    weight: 30
  - name: Robots
    url: /robots-gallery/
    weight: 40
  - name: About
    url: /authors/admin/
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
