# SITE SETUP
# Documentation: https://docs.hugoblox.com/getting-started/

############################
## Theme
############################
appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

############################
## SEO
############################
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Senior Research Scientist at Toyota Research Institute. Robot foundation models, tactile sensing, contact-rich manipulation.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

############################
## Site Header
############################
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

############################
## Site Footer
############################
footer:
  copyright:
    notice: 'Â© {year} Naveen Kuppuswamy. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

############################
## Localization
############################
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

############################
## Site Features
############################
features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/naveenoid/naveenoid.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
